// Generated by LiveScript 1.5.0
(function(){
  var fs;
  fs = require('fs');
  describe('Basic', function(_){
    var reactify, compiler;
    reactify = require('../reactify.js');
    compiler = require('livescript');
    it('load', function(){
      var code;
      code = reactify(fs.readFileSync('./files/basic.ls').toString('utf-8'));
      console.log(code.ls);
    });
  });
}).call(this);
